### ISSUE TITLE
Handle overdrunk,

### ISSUE THREAD

**Issue by Veracity0** [Veracity0/shadow-rift#10]
Shadow Rift ingresses are place.php locations that redirect to adventure.php.
If you are overdrunk, adventure.php sends you to Drunken Stupor.
However, if you have Drunkula's wineglass equipped in your offhand, you can adventure there.
The drawback is that you can only use physical attacks.

That might be adequate here - especially if you are simply buying shadow items to fulfill an "items" quest.

1) If you are overdrunk and don't have (or can't equip) Drunkula's wineglass, abort.
2) If you are overdrunk and have and can equip Drunkula's wineglass, retrieve_item() it and include "+equip Drunkula's wineglass" int the maximizer string.

**Comment by horrible-little-slime** [comment]
You might want to use the [space tourist phaser](https://kol.coldfront.net/thekolwiki/index.php/Space_Tourist_Phaser) alongside the wineglass to bypass shadow monsters' physical resistance

**Comment by Veracity0** [comment]
> You might want to use the [space tourist phaser](https://kol.coldfront.net/thekolwiki/index.php/Space_Tourist_Phaser) alongside the wineglass to bypass shadow monsters' physical resistance

That's a good idea.

I added a ShadowRiftConsult.ash script which knows to use "attack with weapon" if the wine glass is equipped. So, it will depend on your weapon - and elemental damage accessories - to determine how effective your attacks are.

I expect I will still maximize for Item Drop, but will then equip wineglass after other equipment is is donned.
Equipping the phaser would be easy. There are hundreds of them min priced in the mall.

Doing a retrieve_item on the phaser when running this script while overdrunk seems perfectly reasonable.

**Comment by Veracity0** [comment]
PR #17 does this:

1) If you are overdrunk and have and can equip Drunkula's wineglass, allow script to execute.
2) Equip Drunkula's wineglass before entering a Shadow Rift - even if it will be only to use your shadow lodestone.
3) Require a Space Tourist Phaser, if you will be entering combats, and include it in the maximizer expression we use when suiting up before adventuring that will include combats.

(As part of a different issue - from same PR - I verified that using JUST a Space Tourist Phaser is just dandy for killing shadow critters without Silent Treatment, combat spells, or combat items - except for the shadow matrix. :)

This issue should be resolved.
