### ISSUE TITLE
Improve combat support

### ISSUE THREAD

**Issue by Veracity0** [Veracity0/shadow-rift#12]
We require the user to set up their CCS to be able to handle any shadow monster they will encounter.
That is easy to do for the regular monsters; they scale, but are pretty weak.

My CCS does this:
```
[ shadow rift ]
try to steal an item
skill pocket crumbs
skill extract
skill silent treatment
skill saucegeyser
```

I do not currently have CCS entries for the six shadow bosses.

- pickpocket is ineffective; they have guaranteed drops of two specific items, each.
- shadow scythe does 90% of your Maximum HP each round and always gets the drop. You need to one-shot it.
- shadow spire does 30-35% of your Maximum HP each round. You need to, at worst, two-shot it.
- shadow tongue and shadow cauldron do passive elemental damage every round.
- shadow matrix blocks physical attacks.
- shadow orrery reflects spells. Elemental items work well against it.

We currently have a function - prepare_for_boss() - which is called before calling adv1 to fight the boss.
It currently just restores your HP to 100%. That is necessary for the scythe and spire, at least.

1) Is there anything else we could/should do to make your CCS have a better chance of defeating the boss?

I think requiring the user to set up their CCS for such is reasonable; they know best which resources they'd like to spend.
But, when I first thought about this script, I imagined providing a consult script or something that could handle all the shadow monsters and bosses.

2) That sounds complicated. Perhaps we provide a heavily commented template for a consult script that recognizes the 6 bosses and the mundane shadow monsters and tells the user what they need to be able to handle?

**Comment by magus-prime** [comment]
The only ones that I had to do anything other than:
[ shadow ] 
skill silent treatment
skill saucegeyser

were the orrey (silent treatment and gas can) and the scythe (saucegeyser)

**Comment by Veracity0** [comment]
PR https://github.com/Veracity0/shadow-rift/pull/14  provides a thoroughly documented consult script.
It encapsulates your your suggestions.

**Comment by Veracity0** [comment]
I'm happy with this. That PR is merged and I consider this ussue to be resolved.

**Comment by Veracity0** [comment]
I am reopening this.

I am happy with ShadowRiftConsult.ash.
You can configure a combat spell and a combat item to use.
But what if you really don't have a good combat spell available?

Turns out, there is a really good weapon which could be used.
As @horrible-little-slime pointed out in another issue, the [space tourist phaser](https://kol.coldfront.net/thekolwiki/index.php/Space_Tourist_Phaser) converts all your physical damage into random elemental damage, thereby bypassing physical resistance.

I propose that if VSR.CombatSpell is set to "none" (or we are overdrunk and will be using Drunkula's wineglass) that we "acquire" that weapon (hundreds of which are min-priced in the mall) and add "+equip Space Tourist Phaser" to the maximizer string.

**Comment by Veracity0** [comment]
Now that we have a capable and configurable ShadowRiftConsult.ash, how about if we provide easy CCS support?

We want a CCS that contains simply:
```
[ shadow rift ]
consult ShadowRiftConsult.ash
```

If configured to create/use a CCS:

If shadow_rift.ccs does not exist:
    create one containing exactly that rule using write_ccs
set_ccs("shadow_rift");

... surrounded by a try/finally to save/restore "customCombatScript" property.

**Comment by Veracity0** [comment]
PR https://github.com/Veracity0/shadow-rift/pull/17 does this:

1) VSR.UseShadowRiftConsult will (create and) switch to shadow-rift.ccs, which contains this:
```
[ shadow rift ]
consult ShadowRiftConsult.ash
```

2) VSR.UseSpaceTouristPhaser will add ``` +equip Space Tourist Phaser``` to the maximizer expression when suiting up.
With that item equipped, you can go quite far (given high enough attack power) without needing Silent Treatment, a combat spell, or a combat item. The one exception being the shadow matrix, which blocks physical attacks.

3) If you are overdrunk and have and can equip Drunkula's wineglass, we will allow adventuring and will automatically equip the wineglass. If you will have combats (rather than just visiting a Shadow Rift to use a shadow lodestone), we will require - and equip - a Space Tourist Phaser.

I think this will do it for this issue; I am happy with ShadowRiftConsult.ash and it is easy to install and use it.
